subgoal_objective:
  _target_: nuplan.planning.training.modeling.objectives.subgoal_objective.SubgoalObjective
  _convert_: 'all'

  weight: 1.0                  # weight contribution to the overall loss
