_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: 'all'

scenario_types:                     # List of scenario types to include
  - changing_lane 
scenario_tokens:                    # List of scenario tokens to include
  - 49e45364d9d55b37
  - 457238fe173052e9
  - 53ebedd520395ec4 
  - 4b3b50a9f58b5d79 
  - 2d4fa9eb37155845 
  - 1002b6dd3f745b1b 
  - 99822c6ea67c5cb2 
  - b0ee5b8c26b0582b 
  - c0f1326b41465187 
  - caaab29c36ef5bee 
  - c0a9f2a2cfd357c5 
  - cafbf36585ad5136 
  - eb241d431d4d50d8 
  - e9b30fc73b785460 
  - fb7742eb940853b5 
  - f7b8320599e7561d 

log_names:                          # Filter scenarios by log names
  - 2021.07.24.22.53.21_veh-47_00045_00901
  - 2021.07.24.20.02.23_veh-47_00005_00767
  - 2021.06.07.12.42.11_veh-38_04779_06284
  - 2021.07.24.22.52.16_veh-35_04956_06521
  - 2021.09.14.18.43.41_veh-45_00196_00578
  - 2021.07.24.18.06.35_veh-35_00016_03642
  - 2021.09.13.14.16.34_veh-28_00363_00529
  - 2021.07.24.16.48.51_veh-17_04593_05398
  - 2021.06.07.17.46.49_veh-35_00923_01536
  - 2021.06.08.17.25.03_veh-35_00359_00894
  - 2021.07.24.18.06.35_veh-35_00016_03642
  - 2021.07.24.15.54.20_veh-47_03573_05252
  - 2021.06.08.18.59.48_veh-12_04090_04528
  - 2021.07.24.18.06.35_veh-35_00016_03642
  - 2021.06.07.18.29.03_veh-16_00049_00824
  - 2021.09.23.03.06.36_veh-49_01456_01840
map_names: null

num_scenarios_per_type: null           # Number of scenarios per type
limit_total_scenarios: null         # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s: null         # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.

expand_scenarios: false             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: true          # Whether to remove scenarios where the mission goal is invalid
shuffle: true                      # Whether to shuffle the scenarios
