_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: 'all'

scenario_types:                     # List of scenario types to include
  - stopping_with_lead
scenario_tokens:                    # List of scenario tokens to include
  - 9cda228a422a5fb1

log_names:                          # Filter scenarios by log names
  - 2021.06.07.13.42.27_veh-47_00299_00588
map_names: null

num_scenarios_per_type: 1           # Number of scenarios per type
limit_total_scenarios: null         # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s: null         # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.

expand_scenarios: false             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: true          # Whether to remove scenarios where the mission goal is invalid
shuffle: false                      # Whether to shuffle the scenarios

# behind_long_vehicle__2021.06.07.12.42.11_veh-38_00741_01497__15416947b62a540e__1017-0328
# starting_left_turn__2021.09.14.15.03.51_veh-45_01205_01789__6050f41df75a5ab8
# starting_straight_traffic_light_intersection_traversal__2021.07.24.23.59.52_veh-12_03414_04602__5f7dd09ab72c50f8__1021-1831
# starting_left_turn__2021.09.14.17.35.14_veh-45_01816_01995__5a84205b674e5af7__1023-2123
# following_lane_with_lead__2021.07.24.22.53.21_veh-47_03396_04635__197ef7518e4657b2
# stopping_with_lead__2021.06.07.13.42.27_veh-47_00299_00588__9cda228a422a5fb1__1023-2237