_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: 'all'

scenario_types:                     # List of scenario types to include
  - starting_straight_traffic_light_intersection_traversal
scenario_tokens:                    # List of scenario tokens to include
  - 162b92f3a7905adc

log_names:                          # Filter scenarios by log names
  - 2021.08.24.17.01.06_veh-45_00228_00689
map_names: null

num_scenarios_per_type: 1           # Number of scenarios per type
limit_total_scenarios: null         # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s: null         # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.

expand_scenarios: false             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: true          # Whether to remove scenarios where the mission goal is invalid
shuffle: false                      # Whether to shuffle the scenarios

# starting_right_turn__2021.09.14.19.46.05_veh-45_01029_01458__1acc0a08688c5c99__1016-1415
# starting_right_turn__2021.09.14.18.43.41_veh-45_00196_00578__25b971ffad8d5c53__1016-1425
# starting_straight_traffic_light_intersection_traversal__2021.08.24.17.01.06_veh-45_00228_00689__162b92f3a7905adc__1016-2143