_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: 'all'

scenario_types:                     # List of scenario types to include
  - behind_long_vehicle 
scenario_tokens:                    # List of scenario tokens to include
  - a81d831747125494

log_names:                          # Filter scenarios by log names
  - 2021.07.24.00.58.02_veh-12_01831_03390
map_names: null

num_scenarios_per_type: 1           # Number of scenarios per type
limit_total_scenarios: null         # Limit total scenarios (float = fraction, int = num) - this filter can be applied on top of num_scenarios_per_type
timestamp_threshold_s: null         # Filter scenarios to ensure scenarios have more than `timestamp_threshold_s` seconds between their initial lidar timestamps
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.

expand_scenarios: false             # Whether to expand multi-sample scenarios to multiple single-sample scenarios
remove_invalid_goals: true          # Whether to remove scenarios where the mission goal is invalid
shuffle: false                      # Whether to shuffle the scenarios

# starting_right_turn - 2021.07.24.22.53.21_veh-47_01429_03205 - 5ba475c6dd885918
# high_lateral_acceleration__2021.07.24.22.58.17_veh-37_00207_03083__842a25b8cf2855e3__1111-0731
# low_magnitude_speed__2021.09.14.19.46.05_veh-45_00086_00843__d6a462e2c67f54fe__1111-0851
# starting_right_turn__2021.10.05.04.38.41_veh-50_00996_01109__3b5ea626aaa8534a__1111-0554
# high_magnitude_speed__2021.07.24.16.48.51_veh-17_03292_03530__4ea1ebde0a295bfc__1111-0624
# behind_long_vehicle__2021.07.24.00.58.02_veh-12_01831_03390__a81d831747125494__1111-0817